<?php
/**
 * Copyright © 2017 Storeplugins. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Storeplugins\Paychant\Block\Form
 */
?>
<?php $methodCode = $block->escapeHtml($block->getMethodCode());?>
<div class="items <?php /* @noEscape */ echo $methodCode ?> instructions agreement checkout-agreement-item-content" id="payment_form_<?php /* @noEscape */ echo $methodCode ?>" style="display: none;">
    <?php /* @noEscape */ echo nl2br($block->escapeHtml($instructions)) ?>
    <div style="padding:10px 15px 15px;">
        <img src="<?php $block->escapeUrl($block->getViewFileUrl('Storeplugins_Paychant::icon_accepted.png'));?>" alt="<?php echo __('Checkout via Paychant'); ?>"><br>
    </div>
</div>
