<?php
/**
 * Copyright © 2017 Storeplugins. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Storeplugins\Paychant\Block\Info
 */
?>
<?php echo $this->escapeHtml($block->getMethod()->getTitle()) ?>
    {{pdf_row_separator}}
<?php echo __('Paychant Transaction ID: %1', $this->escapeHtml($block->getInfo()->getLastTransId())) ?>
    {{pdf_row_separator}}
